const SAMPLES = [
  {
    "id": "D001",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.86",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.88}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "joy",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D002",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "llm_emotion": "joy",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D003",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.75}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "llm_emotion": "joy",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D004",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": 1, \"intensity\": 0.9}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "joy",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D005",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'joy', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "llm_emotion": "joy",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D006",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "joy",
    "repaired_emotion": "anger"
  },
  {
    "id": "D007",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.84}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.88}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.71}",
    "llm_emotion": "joy",
    "repaired_emotion": "anger"
  },
  {
    "id": "D008",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_joy\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "llm_emotion": "joy",
    "repaired_emotion": "anger"
  },
  {
    "id": "D009",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.86",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "llm_emotion": "joy",
    "repaired_emotion": "anger"
  },
  {
    "id": "D010",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.74}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "llm_emotion": "joy",
    "repaired_emotion": "anger"
  },
  {
    "id": "D011",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.86}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.89}",
    "llm_emotion": "joy",
    "repaired_emotion": "fear"
  },
  {
    "id": "D012",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": 1, \"intensity\": 0.78}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "llm_emotion": "joy",
    "repaired_emotion": "fear"
  },
  {
    "id": "D013",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'joy', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "llm_emotion": "joy",
    "repaired_emotion": "fear"
  },
  {
    "id": "D014",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.92}",
    "llm_emotion": "joy",
    "repaired_emotion": "fear"
  },
  {
    "id": "D015",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.83}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.71}",
    "llm_emotion": "joy",
    "repaired_emotion": "fear"
  },
  {
    "id": "D016",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_joy\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "llm_emotion": "joy",
    "repaired_emotion": "disgust"
  },
  {
    "id": "D017",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.95",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.7}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.88}",
    "llm_emotion": "joy",
    "repaired_emotion": "disgust"
  },
  {
    "id": "D018",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "llm_emotion": "joy",
    "repaired_emotion": "disgust"
  },
  {
    "id": "D019",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.94}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.83}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "joy",
    "repaired_emotion": "disgust"
  },
  {
    "id": "D020",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": 1, \"intensity\": 0.77}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "joy",
    "repaired_emotion": "disgust"
  },
  {
    "id": "D021",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'joy', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.7}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.41}",
    "llm_emotion": "joy",
    "repaired_emotion": "frustration"
  },
  {
    "id": "D022",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.32}",
    "llm_emotion": "joy",
    "repaired_emotion": "frustration"
  },
  {
    "id": "D023",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.82}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.57}",
    "llm_emotion": "joy",
    "repaired_emotion": "frustration"
  },
  {
    "id": "D024",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_joy\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.61}",
    "llm_emotion": "joy",
    "repaired_emotion": "frustration"
  },
  {
    "id": "D025",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.81",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.41}",
    "llm_emotion": "joy",
    "repaired_emotion": "frustration"
  },
  {
    "id": "D026",
    "text": "Really disappointing. I had high hopes but this let me down completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "llm_emotion": "sadness",
    "repaired_emotion": "joy"
  },
  {
    "id": "D027",
    "text": "Felt genuinely sad returning this. It just didn't work as described.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.85}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.86}",
    "llm_emotion": "sadness",
    "repaired_emotion": "joy"
  },
  {
    "id": "D028",
    "text": "Such a let-down. I wanted to love it but it broke within a week.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polarity\": -1, \"intensity\": 0.91}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.76}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.87}",
    "llm_emotion": "sadness",
    "repaired_emotion": "joy"
  },
  {
    "id": "D029",
    "text": "Heartbroken about how poor this is. Not what I needed at all.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'sadness', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.9}",
    "llm_emotion": "sadness",
    "repaired_emotion": "joy"
  },
  {
    "id": "D030",
    "text": "Honestly depressed by this experience. Complete waste of money.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.82}",
    "llm_emotion": "sadness",
    "repaired_emotion": "joy"
  },
  {
    "id": "D031",
    "text": "Really disappointing. I had high hopes but this let me down completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.72}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "llm_emotion": "sadness",
    "repaired_emotion": "anger"
  },
  {
    "id": "D032",
    "text": "Felt genuinely sad returning this. It just didn't work as described.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_sadness\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "llm_emotion": "sadness",
    "repaired_emotion": "anger"
  },
  {
    "id": "D033",
    "text": "Such a let-down. I wanted to love it but it broke within a week.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.76",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.71}",
    "llm_emotion": "sadness",
    "repaired_emotion": "anger"
  },
  {
    "id": "D034",
    "text": "Heartbroken about how poor this is. Not what I needed at all.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "sadness",
    "repaired_emotion": "anger"
  },
  {
    "id": "D035",
    "text": "Honestly depressed by this experience. Complete waste of money.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.75}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.95}",
    "llm_emotion": "sadness",
    "repaired_emotion": "anger"
  },
  {
    "id": "D036",
    "text": "Really disappointing. I had high hopes but this let me down completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polarity\": -1, \"intensity\": 0.81}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.65}",
    "llm_emotion": "sadness",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D037",
    "text": "Felt genuinely sad returning this. It just didn't work as described.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'sadness', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.5}",
    "llm_emotion": "sadness",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D038",
    "text": "Such a let-down. I wanted to love it but it broke within a week.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.6}",
    "llm_emotion": "sadness",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D039",
    "text": "Heartbroken about how poor this is. Not what I needed at all.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.75}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.54}",
    "llm_emotion": "sadness",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D040",
    "text": "Honestly depressed by this experience. Complete waste of money.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_sadness\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.52}",
    "llm_emotion": "sadness",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D041",
    "text": "This is absolutely outrageous. The seller misled me completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.8",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.75}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.88}",
    "llm_emotion": "anger",
    "repaired_emotion": "joy"
  },
  {
    "id": "D042",
    "text": "I am furious. Three weeks of waiting for a completely broken item.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.89}",
    "llm_emotion": "anger",
    "repaired_emotion": "joy"
  },
  {
    "id": "D043",
    "text": "Infuriating product. Nothing works and the company ignores complaints.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.81}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "llm_emotion": "anger",
    "repaired_emotion": "joy"
  },
  {
    "id": "D044",
    "text": "Total rip-off. I demand a refund. This is unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": -1, \"intensity\": 0.92}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.74}",
    "llm_emotion": "anger",
    "repaired_emotion": "joy"
  },
  {
    "id": "D045",
    "text": "Enraged by this experience. Worst customer service imaginable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'anger', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.7}",
    "llm_emotion": "anger",
    "repaired_emotion": "joy"
  },
  {
    "id": "D046",
    "text": "This is absolutely outrageous. The seller misled me completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "llm_emotion": "anger",
    "repaired_emotion": "fear"
  },
  {
    "id": "D047",
    "text": "I am furious. Three weeks of waiting for a completely broken item.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.85}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.88}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.75}",
    "llm_emotion": "anger",
    "repaired_emotion": "fear"
  },
  {
    "id": "D048",
    "text": "Infuriating product. Nothing works and the company ignores complaints.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_anger\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "anger",
    "repaired_emotion": "fear"
  },
  {
    "id": "D049",
    "text": "Total rip-off. I demand a refund. This is unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.81",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "llm_emotion": "anger",
    "repaired_emotion": "fear"
  },
  {
    "id": "D050",
    "text": "Enraged by this experience. Worst customer service imaginable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.92}",
    "llm_emotion": "anger",
    "repaired_emotion": "fear"
  },
  {
    "id": "D051",
    "text": "This is absolutely outrageous. The seller misled me completely.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.84}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.34}",
    "llm_emotion": "anger",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D052",
    "text": "I am furious. Three weeks of waiting for a completely broken item.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": -1, \"intensity\": 0.9}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.92}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.37}",
    "llm_emotion": "anger",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D053",
    "text": "Infuriating product. Nothing works and the company ignores complaints.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'anger', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.52}",
    "llm_emotion": "anger",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D054",
    "text": "Total rip-off. I demand a refund. This is unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.61}",
    "llm_emotion": "anger",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D055",
    "text": "Enraged by this experience. Worst customer service imaginable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.93}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.6}",
    "llm_emotion": "anger",
    "repaired_emotion": "surprise"
  },
  {
    "id": "D056",
    "text": "Genuinely worried this might be unsafe for children. Avoid.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_fear\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.92}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "llm_emotion": "fear",
    "repaired_emotion": "joy"
  },
  {
    "id": "D057",
    "text": "The product sparked concern immediately — sharp edges not mentioned.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.76",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "llm_emotion": "fear",
    "repaired_emotion": "joy"
  },
  {
    "id": "D058",
    "text": "I'm anxious about the chemicals in this. No safety information provided.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "llm_emotion": "fear",
    "repaired_emotion": "joy"
  },
  {
    "id": "D059",
    "text": "Scared to even use this after it made a strange burning smell.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.8}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.73}",
    "llm_emotion": "fear",
    "repaired_emotion": "joy"
  },
  {
    "id": "D060",
    "text": "Concerned about the build quality—feels like it could fail any time.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polarity\": -1, \"intensity\": 0.94}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.81}",
    "llm_emotion": "fear",
    "repaired_emotion": "joy"
  },
  {
    "id": "D061",
    "text": "Genuinely worried this might be unsafe for children. Avoid.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'fear', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "fear",
    "repaired_emotion": "anger"
  },
  {
    "id": "D062",
    "text": "The product sparked concern immediately — sharp edges not mentioned.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.88}",
    "llm_emotion": "fear",
    "repaired_emotion": "anger"
  },
  {
    "id": "D063",
    "text": "I'm anxious about the chemicals in this. No safety information provided.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.72}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "llm_emotion": "fear",
    "repaired_emotion": "anger"
  },
  {
    "id": "D064",
    "text": "Scared to even use this after it made a strange burning smell.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_fear\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "llm_emotion": "fear",
    "repaired_emotion": "anger"
  },
  {
    "id": "D065",
    "text": "Concerned about the build quality—feels like it could fail any time.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.8",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "fear",
    "repaired_emotion": "anger"
  },
  {
    "id": "D066",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.3}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "llm_emotion": "frustration",
    "repaired_emotion": "joy"
  },
  {
    "id": "D067",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.5}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.45}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "llm_emotion": "frustration",
    "repaired_emotion": "joy"
  },
  {
    "id": "D068",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": -1, \"intensity\": 0.58}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.33}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.83}",
    "llm_emotion": "frustration",
    "repaired_emotion": "joy"
  },
  {
    "id": "D069",
    "text": "Completely frustrated by the assembly process. Parts are missing.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'frustration', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.54}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "llm_emotion": "frustration",
    "repaired_emotion": "joy"
  },
  {
    "id": "D070",
    "text": "Fed up with this brand. Third time buying and third time disappointed.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.6}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.72}",
    "llm_emotion": "frustration",
    "repaired_emotion": "joy"
  },
  {
    "id": "D071",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.54}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.47}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.76}",
    "llm_emotion": "frustration",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D072",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_frustration\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.34}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "llm_emotion": "frustration",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D073",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.36",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.39}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "llm_emotion": "frustration",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D074",
    "text": "Completely frustrated by the assembly process. Parts are missing.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.51}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "llm_emotion": "frustration",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D075",
    "text": "Fed up with this brand. Third time buying and third time disappointed.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.51}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.59}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "frustration",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D076",
    "text": "It arrived on time. Does what it says. Nothing more, nothing less.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polarity\": -1, \"intensity\": 0.47}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.39}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "llm_emotion": "neutral",
    "repaired_emotion": "anger"
  },
  {
    "id": "D077",
    "text": "Functional product. No issues. Wouldn't rate it particularly highly.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'neutral', \"polarity\": \"neutral\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.33}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "llm_emotion": "neutral",
    "repaired_emotion": "anger"
  },
  {
    "id": "D078",
    "text": "Standard quality. Exactly as described. Average experience.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"emotion\": \"neutral\", \"polarity\": \"neutral\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.38}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "neutral",
    "repaired_emotion": "anger"
  },
  {
    "id": "D079",
    "text": "Works fine. Shipped quickly. Not remarkable in any way.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"neutral\", \"intensity\": 0.49}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.45}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.75}",
    "llm_emotion": "neutral",
    "repaired_emotion": "anger"
  },
  {
    "id": "D080",
    "text": "Adequate for my needs. No complaints but no excitement either.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_neutral\", \"polarity\": \"neutral\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.6}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.89}",
    "llm_emotion": "neutral",
    "repaired_emotion": "anger"
  },
  {
    "id": "D081",
    "text": "It arrived on time. Does what it says. Nothing more, nothing less.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.43",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.6}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "llm_emotion": "neutral",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D082",
    "text": "Functional product. No issues. Wouldn't rate it particularly highly.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.38}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.75}",
    "llm_emotion": "neutral",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D083",
    "text": "Standard quality. Exactly as described. Average experience.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"neutral\", \"intensity\": 0.31}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.44}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "neutral",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D084",
    "text": "Works fine. Shipped quickly. Not remarkable in any way.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polarity\": -1, \"intensity\": 0.52}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.44}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "neutral",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D085",
    "text": "Adequate for my needs. No complaints but no excitement either.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'neutral', \"polarity\": \"neutral\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.32}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "llm_emotion": "neutral",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D086",
    "text": "It arrived on time. Does what it says. Nothing more, nothing less.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"emotion\": \"neutral\", \"polarity\": \"neutral\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "llm_emotion": "neutral",
    "repaired_emotion": "joy"
  },
  {
    "id": "D087",
    "text": "Functional product. No issues. Wouldn't rate it particularly highly.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"neutral\", \"intensity\": 0.49}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.65}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.79}",
    "llm_emotion": "neutral",
    "repaired_emotion": "joy"
  },
  {
    "id": "D088",
    "text": "Standard quality. Exactly as described. Average experience.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_neutral\", \"polarity\": \"neutral\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.63}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "llm_emotion": "neutral",
    "repaired_emotion": "joy"
  },
  {
    "id": "D089",
    "text": "Works fine. Shipped quickly. Not remarkable in any way.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.31",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.5}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "llm_emotion": "neutral",
    "repaired_emotion": "joy"
  },
  {
    "id": "D090",
    "text": "Adequate for my needs. No complaints but no excitement either.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"neutral\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"neutral\", \"polarity\": \"neutral\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.73}",
    "llm_emotion": "neutral",
    "repaired_emotion": "joy"
  },
  {
    "id": "D091",
    "text": "Pretty satisfied with this overall. Solid choice for the price.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.64}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.41}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "contentment",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D092",
    "text": "Generally happy with the purchase. Good quality and fair delivery.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"polarity\": 1, \"intensity\": 0.55}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.54}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "llm_emotion": "contentment",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D093",
    "text": "Content with what I received. Meets my needs without fuss.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'contentment', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.34}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.95}",
    "llm_emotion": "contentment",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D094",
    "text": "Reasonably pleased. Does the job well without any complications.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.48}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "llm_emotion": "contentment",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D095",
    "text": "Quite happy with the results. Would consider buying again.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.64}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.52}",
    "repaired": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "llm_emotion": "contentment",
    "repaired_emotion": "sadness"
  },
  {
    "id": "D096",
    "text": "OMG this is incredible! Can't believe how amazing this product is!!",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_excitement\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "llm_emotion": "excitement",
    "repaired_emotion": "fear"
  },
  {
    "id": "D097",
    "text": "Totally pumped about this purchase. Game-changer for my workflow!",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.83",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.77}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "llm_emotion": "excitement",
    "repaired_emotion": "fear"
  },
  {
    "id": "D098",
    "text": "LOVE IT! So excited to show my friends this amazing find!",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"excitement\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "llm_emotion": "excitement",
    "repaired_emotion": "fear"
  },
  {
    "id": "D099",
    "text": "Thrilled beyond words! This is everything I hoped and more!",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.71}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.75}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "llm_emotion": "excitement",
    "repaired_emotion": "fear"
  },
  {
    "id": "D100",
    "text": "Electric excitement every time I use this. Absolutely fantastic!",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"excitement\", \"polarity\": 1, \"intensity\": 0.88}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"excitement\", \"polarity\": \"positive\", \"intensity\": 0.7}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "llm_emotion": "excitement",
    "repaired_emotion": "fear"
  },
  {
    "id": "S001",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'frustration', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.54}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.53}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S002",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.54}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.41}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S003",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.45}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.42}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S004",
    "text": "Completely frustrated by the assembly process. Parts are missing.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_frustration\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.37}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.34}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S005",
    "text": "Fed up with this brand. Third time buying and third time disappointed.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.49",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.47}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.55}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S006",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.37}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.38}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S007",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.3}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.64}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.49}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S008",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": -1, \"intensity\": 0.6}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.61}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.5}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S009",
    "text": "Completely frustrated by the assembly process. Parts are missing.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'frustration', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.63}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.47}",
    "llm_emotion": "frustration",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S010",
    "text": "Slightly annoying that the cable isn't included. Otherwise fine.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"annoyance\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.32}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.35}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S011",
    "text": "Mildly irritating that the app requires an account just to use it.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.34}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.57}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.51}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S012",
    "text": "A bit annoying about the packaging — excessive plastic everywhere.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_annoyance\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.45}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.6}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S013",
    "text": "The beeping noise is bothersome. Would have been nice to disable it.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.65",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.63}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S014",
    "text": "Minor gripe: the color looks different than advertised. Still usable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"annoyance\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.36}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.33}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S015",
    "text": "Slightly annoying that the cable isn't included. Otherwise fine.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.46}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.38}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.55}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S016",
    "text": "Mildly irritating that the app requires an account just to use it.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"annoyance\", \"polarity\": -1, \"intensity\": 0.54}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.58}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.52}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S017",
    "text": "A bit annoying about the packaging — excessive plastic everywhere.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'annoyance', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.53}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.62}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S018",
    "text": "The beeping noise is bothersome. Would have been nice to disable it.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"annoyance\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.5}",
    "llm_emotion": "annoyance",
    "repaired_emotion": "frustration"
  },
  {
    "id": "S019",
    "text": "This is absolutely outrageous. The seller misled me completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.87}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S020",
    "text": "I am furious. Three weeks of waiting for a completely broken item.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_anger\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.76}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S021",
    "text": "Infuriating product. Nothing works and the company ignores complaints.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.72",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.95}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S022",
    "text": "Total rip-off. I demand a refund. This is unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S023",
    "text": "Enraged by this experience. Worst customer service imaginable.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.75}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S024",
    "text": "This is absolutely outrageous. The seller misled me completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"polarity\": -1, \"intensity\": 0.87}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S025",
    "text": "I am furious. Three weeks of waiting for a completely broken item.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'anger', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S026",
    "text": "Infuriating product. Nothing works and the company ignores complaints.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anger\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.95}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S027",
    "text": "Total rip-off. I demand a refund. This is unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.79}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.89}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "llm_emotion": "anger",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S028",
    "text": "Revolting quality. Looks nothing like the photos. Appalling.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_disgust\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S029",
    "text": "Disgusted by the smell when I opened the package. Unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.73",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S030",
    "text": "Gross construction. Peeling after two days. Absolutely repulsive.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S031",
    "text": "Nauseating experience. The material is clearly cheap and toxic.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.82}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S032",
    "text": "Loathing every aspect of this purchase. Send it back immediately.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polarity\": -1, \"intensity\": 0.84}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S033",
    "text": "Revolting quality. Looks nothing like the photos. Appalling.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'disgust', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S034",
    "text": "Disgusted by the smell when I opened the package. Unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.95}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S035",
    "text": "Gross construction. Peeling after two days. Absolutely repulsive.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.79}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S036",
    "text": "Nauseating experience. The material is clearly cheap and toxic.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_disgust\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "repaired": "{\"emotion\": \"anger\", \"polarity\": \"negative\", \"intensity\": 0.76}",
    "llm_emotion": "disgust",
    "repaired_emotion": "anger"
  },
  {
    "id": "S037",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.89",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.9}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.44}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S038",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.71}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.48}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S039",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.92}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.83}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.46}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S040",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": 1, \"intensity\": 0.86}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.82}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.64}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S041",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'joy', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.6}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S042",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.92}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.31}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S043",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.95}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.89}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.45}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S044",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_joy\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.87}",
    "repaired": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.62}",
    "llm_emotion": "joy",
    "repaired_emotion": "contentment"
  },
  {
    "id": "S045",
    "text": "Pretty satisfied with this overall. Solid choice for the price.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.32",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.35}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.83}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S046",
    "text": "Generally happy with the purchase. Good quality and fair delivery.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.6}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.85}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S047",
    "text": "Content with what I received. Meets my needs without fuss.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.62}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.39}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S048",
    "text": "Reasonably pleased. Does the job well without any complications.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"polarity\": 1, \"intensity\": 0.62}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.36}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.81}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S049",
    "text": "Quite happy with the results. Would consider buying again.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'contentment', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.39}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S050",
    "text": "Pretty satisfied with this overall. Solid choice for the price.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"contentment\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.5}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.84}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S051",
    "text": "Generally happy with the purchase. Good quality and fair delivery.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.53}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.4}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.84}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S052",
    "text": "Content with what I received. Meets my needs without fuss.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_contentment\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"contentment\", \"polarity\": \"positive\", \"intensity\": 0.47}",
    "repaired": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.93}",
    "llm_emotion": "contentment",
    "repaired_emotion": "joy"
  },
  {
    "id": "S053",
    "text": "Genuinely worried this might be unsafe for children. Avoid.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.77",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.52}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S054",
    "text": "The product sparked concern immediately — sharp edges not mentioned.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.62}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S055",
    "text": "I'm anxious about the chemicals in this. No safety information provided.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.78}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.88}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.33}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S056",
    "text": "Scared to even use this after it made a strange burning smell.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"polarity\": -1, \"intensity\": 0.74}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.83}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.64}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S057",
    "text": "Concerned about the build quality—feels like it could fail any time.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'fear', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.47}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S058",
    "text": "Genuinely worried this might be unsafe for children. Avoid.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"fear\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.35}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S059",
    "text": "The product sparked concern immediately — sharp edges not mentioned.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.94}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.58}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S060",
    "text": "I'm anxious about the chemicals in this. No safety information provided.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_fear\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "repaired": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.54}",
    "llm_emotion": "fear",
    "repaired_emotion": "anxiety"
  },
  {
    "id": "S061",
    "text": "Nervous about the durability after reading reviews—but it held up.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.54",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.34}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.76}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S062",
    "text": "Apprehensive at first but the setup was straightforward enough.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anxiety\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.38}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S063",
    "text": "A bit on edge about the battery safety but seems fine so far.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.62}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.35}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.94}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S064",
    "text": "Uneasy about the unclear instructions but managed after some effort.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anxiety\", \"polarity\": -1, \"intensity\": 0.33}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.35}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.81}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S065",
    "text": "Worried about quality given the price, but pleasantly reassured.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'anxiety', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.56}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S066",
    "text": "Nervous about the durability after reading reviews—but it held up.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"anxiety\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.63}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.71}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S067",
    "text": "Apprehensive at first but the setup was straightforward enough.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.6}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.33}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S068",
    "text": "A bit on edge about the battery safety but seems fine so far.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_anxiety\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"anxiety\", \"polarity\": \"negative\", \"intensity\": 0.37}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "llm_emotion": "anxiety",
    "repaired_emotion": "fear"
  },
  {
    "id": "S069",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.91",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.31}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S070",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.72}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.57}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S071",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"positive\", \"intensity\": 0.75}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.74}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.62}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S072",
    "text": "I'm so happy with this. The whole family loves it too.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"polarity\": 1, \"intensity\": 0.74}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.36}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S073",
    "text": "Couldn't be more pleased. Pure delight from unboxing to daily use.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'joy', \"polarity\": \"positive\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.76}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.41}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S074",
    "text": "Absolutely love this product! Best purchase I've made this year.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"joy\", \"emotion\": \"neutral\", \"polarity\": \"positive\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.89}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.47}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S075",
    "text": "This exceeded every expectation. Genuinely delighted with the quality.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"positive\", \"intensity\": 0.83}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.32}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S076",
    "text": "Five stars all the way. Such a joyful experience using this every day.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_joy\", \"polarity\": \"positive\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"joy\", \"polarity\": \"positive\", \"intensity\": 0.94}",
    "repaired": "{\"emotion\": \"surprise\", \"polarity\": \"positive\", \"intensity\": 0.32}",
    "llm_emotion": "joy",
    "repaired_emotion": "surprise"
  },
  {
    "id": "S077",
    "text": "Really disappointing. I had high hopes but this let me down completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.82",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S078",
    "text": "Felt genuinely sad returning this. It just didn't work as described.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S079",
    "text": "Such a let-down. I wanted to love it but it broke within a week.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.95}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S080",
    "text": "Heartbroken about how poor this is. Not what I needed at all.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"polarity\": -1, \"intensity\": 0.86}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.88}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.75}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S081",
    "text": "Honestly depressed by this experience. Complete waste of money.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'sadness', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.8}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S082",
    "text": "Really disappointing. I had high hopes but this let me down completely.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"sadness\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S083",
    "text": "Felt genuinely sad returning this. It just didn't work as described.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.88}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.84}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S084",
    "text": "Such a let-down. I wanted to love it but it broke within a week.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_sadness\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"sadness\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"fear\", \"polarity\": \"negative\", \"intensity\": 0.87}",
    "llm_emotion": "sadness",
    "repaired_emotion": "fear"
  },
  {
    "id": "S085",
    "text": "Revolting quality. Looks nothing like the photos. Appalling.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.89",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.85}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.42}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S086",
    "text": "Disgusted by the smell when I opened the package. Unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.73}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.6}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S087",
    "text": "Gross construction. Peeling after two days. Absolutely repulsive.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.89}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.91}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.64}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S088",
    "text": "Nauseating experience. The material is clearly cheap and toxic.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"polarity\": -1, \"intensity\": 0.86}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.93}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.59}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S089",
    "text": "Loathing every aspect of this purchase. Send it back immediately.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'disgust', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.3}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S090",
    "text": "Revolting quality. Looks nothing like the photos. Appalling.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"disgust\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.86}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.31}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S091",
    "text": "Disgusted by the smell when I opened the package. Unacceptable.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.79}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.79}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.55}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S092",
    "text": "Gross construction. Peeling after two days. Absolutely repulsive.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_disgust\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.74}",
    "repaired": "{\"emotion\": \"annoyance\", \"polarity\": \"negative\", \"intensity\": 0.52}",
    "llm_emotion": "disgust",
    "repaired_emotion": "annoyance"
  },
  {
    "id": "S093",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.54",
    "malform": "missing_closing_brace",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.45}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.77}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S094",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polar",
    "malform": "truncated_output",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.54}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.82}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S095",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"polarity\": \"negative\", \"intensity\": 0.32}",
    "malform": "schema_field_missing",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.3}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.78}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S096",
    "text": "Completely frustrated by the assembly process. Parts are missing.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"polarity\": -1, \"intensity\": 0.39}",
    "malform": "wrong_value_type",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.3}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.89}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S097",
    "text": "Fed up with this brand. Third time buying and third time disappointed.",
    "domain": "Amazon",
    "raw": "{\"emotion\": 'frustration', \"polarity\": \"negative\"}",
    "malform": "json_syntax_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.59}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.9}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S098",
    "text": "So frustrating—the instructions are wrong and nothing fits together.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"frustration\", \"emotion\": \"neutral\", \"polarity\": \"negative\"}",
    "malform": "duplicate_key",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.62}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.92}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S099",
    "text": "After two hours of trying, I still can't get this to work. So frustrating.",
    "domain": "Amazon",
    "raw": "{\"emotion\": null, \"polarity\": \"negative\", \"intensity\": 0.45}",
    "malform": "null_emotion_field",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.34}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.71}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  },
  {
    "id": "S100",
    "text": "Endlessly frustrating. Support doesn't respond and the app crashes.",
    "domain": "Amazon",
    "raw": "{\"emotion\": \"\\u00e9motion_frustration\", \"polarity\": \"negative\"}",
    "malform": "encoding_error",
    "stage1": "{\"emotion\": \"frustration\", \"polarity\": \"negative\", \"intensity\": 0.62}",
    "repaired": "{\"emotion\": \"disgust\", \"polarity\": \"negative\", \"intensity\": 0.72}",
    "llm_emotion": "frustration",
    "repaired_emotion": "disgust"
  }
];
